package storemanager;

import Model.CartModel;
import Model.DB;
import Model.KhachHang;
import Model.KhachHangModel;
import Model.LoaiHangModel;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class Cart extends javax.swing.JInternalFrame {
    
    private static KhachHangModel model;

    public Cart() throws SQLException {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        model = new KhachHangModel();
        jtbLoaiHang.getTableHeader().setFont(new Font("jetbrains mono", Font.BOLD, 14));
        loadData();
    }

    public static void loadData() throws SQLException {
        String[] column = {"Mã Hàng", "Tên Hàng", "Số Lượng", "Đơn giá", "Tổng tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(column, 0);
        for (int i = 0; i < Store.cart.size(); i++) {
            CartModel cart = Store.cart.get(i);
            tableModel.addRow(new Object[]{cart.getMaHang(), cart.getTenHang(), cart.getSoLuong(), cart.getDonGia(), cart.getTongTien()});
        }
        DefaultComboBoxModel<KhachHang> cbkhModel = new DefaultComboBoxModel<KhachHang>();
        ResultSet khachHangRs = model.get();
        while (khachHangRs.next()) {
            cbkhModel.addElement(new KhachHang(khachHangRs.getString(1), khachHangRs.getString(2)));
        }
        cbKhachHang.setModel(cbkhModel);
        jtbLoaiHang.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLoaiHang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        cbKhachHang = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setText("Giỏ Hàng");

        jtbLoaiHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jtbLoaiHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbLoaiHang.setGridColor(new java.awt.Color(255, 255, 255));
        jtbLoaiHang.setRowHeight(30);
        jtbLoaiHang.setSelectionBackground(new java.awt.Color(102, 103, 171));
        jtbLoaiHang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jtbLoaiHang);

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Tên khách hàng");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Mã Hoá đơn");

        txtMaHoaDon.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        txtMaHoaDon.setSelectionColor(new java.awt.Color(35, 166, 97));

        btnSua.setBackground(new java.awt.Color(102, 103, 171));
        btnSua.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Xoá");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 103, 171));
        btnThem.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Lập Hoá đơn");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cbKhachHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(cbKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSua))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnThem)
                    .addComponent(cbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            // TODO add your handling code here:
            for (int i = 0; i < Store.cart.size(); i++) {
                if (Store.cart.get(i).getMaHang().equals(jtbLoaiHang.getModel().getValueAt(jtbLoaiHang.getSelectedRow(), 0))) {
                    Store.cart.remove(i);
                }
            }
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            if(txtMaHoaDon.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Chưa nhập mã hoá đơn","Thông báo",0);
                return;
            }
            String maHoaDon = txtMaHoaDon.getText();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            DB db = new DB();
            String sql = "insert into hoadon values(?,?,?,?)";
            PreparedStatement ps = db.getConnection().prepareStatement(sql);
            ps.setString(1, maHoaDon);
            ps.setString(2, dtf.format(now));
            ps.setString(3, cbKhachHang.getModel().getElementAt(cbKhachHang.getSelectedIndex()).getMaKH());
            ps.setString(4, Login.maNV);
            ps.execute();
            for (int i = 0; i < Store.cart.size(); i++) {
                String sql1 = "insert into cthoadon values(?,?,?,?)";
                PreparedStatement ps1 = db.getConnection().prepareStatement(sql1);
                ps1.setString(1, maHoaDon);
                ps1.setString(2, Store.cart.get(i).getMaHang());
                ps1.setInt(3, Store.cart.get(i).getSoLuong());
                ps1.setInt(4, Store.cart.get(i).getDonGia());
                ps1.execute();
            }
            JOptionPane.showMessageDialog(this, "Lập hoá đơn thành công!", "Thông báo", 1);
            CT_HoaDon ctHoaDon = new CT_HoaDon(maHoaDon);
            ctHoaDon.show();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lập hoá đơn thất bại! Mã hoá đơn đã tồn tại", "Lỗi", 0);
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnSua;
    private static javax.swing.JButton btnThem;
    private static javax.swing.JComboBox<KhachHang> cbKhachHang;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jtbLoaiHang;
    private static javax.swing.JTextField txtMaHoaDon;
    // End of variables declaration//GEN-END:variables
}
