package storemanager;

import Model.LoaiHang;
import Model.LoaiHangModel;
import Model.MatHang;
import Model.MatHangModel;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Product extends javax.swing.JInternalFrame {

    private MatHangModel model;

    public Product() throws SQLException {
        initComponents();
        model = new MatHangModel();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        jtbMatHang.getTableHeader().setFont(new Font("jetbrains mono", Font.BOLD, 14));
        loadData();
    }

    public void loadData() throws SQLException {
        String[] column = {"Mã hàng", "Tên hàng", "ĐVT", "Đơn Giá", "Loại Hàng"};
        DefaultTableModel tableModel = new DefaultTableModel(column, 0);
        ResultSet rs = (ResultSet) model.get();
        while (rs.next()) {
            tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getInt(4), rs.getString(5)});
        }
        DefaultComboBoxModel<LoaiHang> cbModel = new DefaultComboBoxModel();

        ResultSet rsLoaiHang = new LoaiHangModel().get();
        while (rsLoaiHang.next()) {
            cbModel.addElement(new LoaiHang(rsLoaiHang.getString(1), rsLoaiHang.getString(2)));
        }
        cbLoaiHang.setModel(cbModel);
        jtbMatHang.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMatHang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtMaHang = new javax.swing.JTextField();
        txtTenHang = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbLoaiHang = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Mặt Hàng");

        jtbMatHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jtbMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jtbMatHang.setGridColor(new java.awt.Color(255, 255, 255));
        jtbMatHang.setRowHeight(30);
        jtbMatHang.setSelectionBackground(new java.awt.Color(102, 103, 171));
        jtbMatHang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtbMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbMatHang);

        btnThem.setBackground(new java.awt.Color(102, 103, 171));
        btnThem.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 103, 171));
        btnSua.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 103, 171));
        btnXoa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(102, 103, 171));
        btnClear.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Nhập Lại");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtMaHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        txtMaHang.setSelectionColor(new java.awt.Color(35, 166, 97));

        txtTenHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtDongia.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtDVT.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Mã Sản Phẩm");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel4.setText("Đơn vị tính");

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel6.setText("Loại Hàng");

        cbLoaiHang.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbLoaiHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDongia)
                            .addComponent(cbLoaiHang, 0, 177, Short.MAX_VALUE))
                        .addGap(176, 176, 176))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cbLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMatHangMouseClicked
        // TODO add your handling code here:
        int row = jtbMatHang.getSelectedRow();
        txtMaHang.setText(jtbMatHang.getModel().getValueAt(row, 0).toString());
        txtTenHang.setText(jtbMatHang.getModel().getValueAt(row, 1).toString());
        txtDVT.setText(jtbMatHang.getModel().getValueAt(row, 2).toString());
        txtDongia.setText(jtbMatHang.getModel().getValueAt(row, 3).toString());
        int index = 0;
        for (int i = 0; i < cbLoaiHang.getItemCount(); i++) {
            LoaiHang lh = cbLoaiHang.getModel().getElementAt(i);
            if (lh.getTenLoai().equals(jtbMatHang.getModel().getValueAt(row, 4).toString())) {
                index = i;
            }
            cbLoaiHang.setSelectedIndex(index);
        }
    }//GEN-LAST:event_jtbMatHangMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        MatHang mh = new MatHang();
        mh.setMaHang(txtMaHang.getText());
        mh.setTenHang(txtTenHang.getText());
        mh.setDvt(txtDVT.getText());
        mh.setLoaiHang(cbLoaiHang.getModel().getElementAt(cbLoaiHang.getSelectedIndex()).getMaLoai());
        if (mh.getDvt().trim().equals("") || mh.getLoaiHang().trim().equals("") || mh.getMaHang().trim().equals("") || mh.getTenHang().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin", "Thông báo", 0);
            return;
        }
        try {
            Integer.parseInt(txtDongia.getText());
            mh.setDongia(Integer.parseInt(txtDongia.getText()));

        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là số");
            return;
        }
        try {
            model.insert(mh);
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", 1);
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại, mã sản phẩm đã tồn tại", "Thông báo", 0);

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        MatHang mh = new MatHang();
        mh.setMaHang(txtMaHang.getText());
        mh.setTenHang(txtTenHang.getText());
        mh.setDvt(txtDVT.getText());
        mh.setLoaiHang(cbLoaiHang.getModel().getElementAt(cbLoaiHang.getSelectedIndex()).getMaLoai());
        if (mh.getDvt().trim().equals("") || mh.getLoaiHang().trim().equals("") || mh.getMaHang().trim().equals("") || mh.getTenHang().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin", "Thông báo", 0);
            return;
        }
        try {
            Integer.parseInt(txtDongia.getText());
            mh.setDongia(Integer.parseInt(txtDongia.getText()));

        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là số");
            return;
        }
        try {
            model.update(mh);
            JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", 1);
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại", "Thông báo", 0);

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaHang.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập mã hàng", "Thông báo", 1);
                return;
            }
            int c = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không?", "Thông báo", 1);
            if (c == 0) {
                model.delete(txtMaHang.getText());
                JOptionPane.showMessageDialog(this, "Xoá thành công", "Thông báo", 1);
                loadData();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Xoá thất bại", "Thông báo", 0);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDVT.setText("");
        txtDongia.setText("");
        txtMaHang.setText("");
        txtTenHang.setText("");
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<LoaiHang> cbLoaiHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbMatHang;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtTenHang;
    // End of variables declaration//GEN-END:variables
}
